name: RelicLabels
version: '1.0.3'
main: de.waifjyux.relicLabels.RelicLabels
author: Waifjyux
api-version: '1.18'

commands:
  reliclabels:
    description: Command for configuring the plugin
    permission: reliclabels.command
    aliases:
    - rls
